#!/bin/bash



# 1-hello_you
echo "#!/bin/bash" > 1-hello_you
echo "echo \"hello \$USER\"" >> 1-hello_you
git add 1-hello_you
git commit -m "Add 1-hello_you"

# 2-path
echo "#!/bin/bash" > 2-path
echo "export PATH=\$PATH:/action" >> 2-path
git add 2-path
git commit -m "Add 2-path"

# 3-paths
echo "#!/bin/bash" > 3-paths
echo "echo \$((\`echo \$PATH | grep -o \":/\" | wc -l\` + 1))" >> 3-paths
git add 3-paths
git commit -m "Add 3-paths"

# 4-global_variables
echo "#!/bin/bash" > 4-global_variables
echo "printenv" >> 4-global_variables
git add 4-global_variables
git commit -m "Add 4-global_variables"

# 5-local_variables
echo "#!/bin/bash" > 5-local_variables
echo "set" >> 5-local_variables
git add 5-local_variables
git commit -m "Add 5-local_variables"

# 6-create_local_variable
echo "#!/bin/bash" > 6-create_local_variable
echo "BEST=\"School\"" >> 6-create_local_variable
git add 6-create_local_variable
git commit -m "Add 6-create_local_variable"

# 7-create_global_variable
echo "#!/bin/bash" > 7-create_global_variable
echo "export BEST=School" >> 7-create_global_variable
git add 7-create_global_variable
git commit -m "Add 7-create_global_variable"

# 8-true_knowledge
echo "#!/bin/bash" > 8-true_knowledge
echo "echo \$((\$TRUEKNOWLEDGE + 128))" >> 8-true_knowledge
git add 8-true_knowledge
git commit -m "Add 8-true_knowledge"

# 9-divide_and_rule
echo "#!/bin/bash" > 9-divide_and_rule
echo "echo \$((\$POWER / \$DIVIDE))" >> 9-divide_and_rule
git add 9-divide_and_rule
git commit -m "Add 9-divide_and_rule"

# 10-love_exponent_breath
echo "#!/bin/bash" > 10-love_exponent_breath
echo "echo \$((BREATH ** \$LOVE))" >> 10-love_exponent_breath
git add 10-love_exponent_breath
git commit -m "Add 10-love_exponent_breath"

# 11-binary_to_decimal
echo "#!/bin/bash" > 11-binary_to_decimal
echo "echo \"\$((2#\$BINARY))\"" >> 11-binary_to_decimal
git add 11-binary_to_decimal
git commit -m "Add 11-binary_to_decimal"

# 12-combinations
echo "#!/bin/bash" > 12-combinations
echo "echo {a..z}{a..z} | tr \" \" \"\n\" | grep -v \"oo\"" >> 12-combinations
git add 12-combinations
git commit -m "Add 12-combinations"

# 13-print_float
echo "#!/bin/bash" > 13-print_float
echo "printf \"%.2f\" \$NUM | sort" >> 13-print_float
git add 13-print_float
git commit -m "Add 13-print_float"

